name: expensetracer
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^0.7.0
  firebase_auth: ^2.0.0
  google_sign_in: ^4.5.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0 
  provider: ^6.0.2
  flutter_datetime_picker: ^1.5.1
  cloud_firestore: ^2.5.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: 
  uses-material-design: true
  assets:
    - assets/icons/googleicon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
